Add failure hooks and test them

diff --git a/.github/workflows/publish-staging-redacted-export.yml b/.github/workflows/publish-staging-redacted-export.yml
--- a/.github/workflows/publish-staging-redacted-export.yml
+++ b/.github/workflows/publish-staging-redacted-export.yml
@@ -118,8 +118,10 @@ jobs:
           TIMESTAMP=$(date +'%F-%H-%M-%S')
           TEMP_DB_SERVICE_NAME=psd-redacted-export-$TIMESTAMP
           FINAL_S3_URL="s3://${S3_BUCKET}/${TIMESTAMP}.sql.gz"
-          echo "::set-output name=temp_db_service_name::$TEMP_DB_SERVICE_NAME"
-          echo "::set-output name=final_s3_url::$FINAL_S3_URL"
+          echo "::set-output name=temp-db-service-name::$TEMP_DB_SERVICE_NAME"
+          echo "::set-output name=final-s3-url::$FINAL_S3_URL"
+          exit 1
+          # ^ TESTING FAILURE
           cf api api.london.cloud.service.gov.uk
           cf auth
           cf target -o 'beis-opss' -s $SPACE
@@ -139,3 +141,23 @@ jobs:
           cf logout
           gzip --keep psd_redacted_export.sql
           aws s3 cp psd_redacted_export.sql.gz $FINAL_S3_URL
+
+    - name: Alert team via Slack of export failure
+      if: failure()
+      env:
+        SLACK_WEBHOOK: ${{ secrets.SlackWebhookUrl }}
+      run: |
+        curl -X POST --data-urlencode "payload={\"channel\": \"#alerts\", \"username\": \"exportbot\", \"text\": \"Redacted export has failed!\n\nCF Service: ${{ steps.export-database.outputs.temp-db-service-name }}\nS3 destination: ${{ steps.export-database.outputs.final-s3-url }}\", \"icon_emoji\": \":disappointed:\"}" $SLACK_WEBHOOK
+
+    - name: Try to delete the temporary DB
+      if: failure()
+      env:
+        SPACE: staging
+        CF_USERNAME: ${{ secrets.PaaSUsernameStaging }}
+        CF_PASSWORD: ${{ secrets.PaaSPasswordStaging }}
+      run: |
+        cf api api.london.cloud.service.gov.uk
+        cf auth
+        cf target -o 'beis-opss' -s $SPACE
+        cf delete-service ${{ steps.export-database.outputs.temp-db-service-name }} -f
+        cf logout
